### ISSUE TITLE
Current on hand buffer status - red zone computation

### ISSUE THREAD

**Issue by JordiBForgeFlow** [ForgeFlow/ddmrp#4]
The red status should occur when the current on hand < Oh hand alert.

On-hand alert = % of red zone (by default 50%).

There should also be an option to display the bufferts that are in alert.

**Comment by LoisRForgeFlow** [comment]
fixed here some time ago: https://github.com/Eficent/ddmrp/commit/1fb43a6140decbf6c7269f3914e9b7a3c0cae44d. To filter buffers in alert you can filter buffer that are in Red for the on-hand status.
