### ISSUE TITLE
replenish_overwrite same as replenish

### ISSUE THREAD

**Issue by szufisher** [ForgeFlow/ddmrp#41]
currently there is replenish_overwrite option available,  per the below definition, after select this option, system will not calculate ADU. but currently either replenish_overwrite or replenish function the same: calc ADU. 

In Demand Driven Planning, parts are designated:
Replenished Parts – the parts strategically chosen to be managed as replenishment parts,  via a color coded buffer management approach. These parts will have dynamic buffers – they’ll increase when demand increases, for example, and decrease when demand decreases.

Replenish Override – also buffered and color-coded but NOT dynamic.

Min/Max – a variation of the classic min/max, with advantages of also being Dynamic; for readily available parts without the strategic value of Replenished parts.

**Comment by LoisRForgeFlow** [comment]
Yes, you are absolutely right, this was in our to-do list but quite forgotten. Thanks for bring it to the spotlight again.

Fixed here: https://github.com/Eficent/ddmrp/pull/48
