### ISSUE TITLE
Qualified demand calculation

### ISSUE THREAD

**Issue by HviorForgeFlow** [ForgeFlow/ddmrp#44]
`_calc_qualified_demand` looks for dates in stock moves using `date` instead of `date_expected`.  If I create an stock moving under order spike threshold for any day it take in to account for today's demand.

**Comment by LoisRForgeFlow** [comment]
This is an issue that happens when manually creating pickings, when they are created from procurements `date` fields is ok. Anyway, it has to be fixed and so it is :wink: see https://github.com/Eficent/ddmrp/commit/0f172f6e552387185933f6621daad3ecc0829dfb

**Comment by LoisRForgeFlow** [comment]
Note: we keep using `date` for done moves domains ([see](https://github.com/Eficent/ddmrp/blob/9.0/ddmrp/models/stock_warehouse_orderpoint.py#L402)) as this is updated with the date of validation.
