### ISSUE TITLE
Extract Decoupled Lead Time (dlt) to product

### ISSUE THREAD

**Issue by hparfr** [ForgeFlow/ddmrp#71]
I think the concept of dlt is really interesting and can be used outside the context of DDMRP.

What do you think of externalize it in a new module, and store it on the product.product and bom ? 
[product.product].dlt will be stored, computed and depends of seller_ids, bom_ids.dlt
[product.template].dlt will be related of product_variant_ids.dlt
[mrp.bom.line].dlt will be a related to product_id.dlt
[mrp.bom].dlt will be stored, computed and depends of product_id.produce_delay, product_template.produce_delay , bom_line_ids.dlt

**Comment by LoisRForgeFlow** [comment]
DLT is a property of a buffer (or product position (product + location)) not a product, it can happen that the same product has two different DLTs for two different buffers/locations.

**Comment by hparfr** [comment]
Correct, I was thinking of a case where each product have a preferred route. Not generic enough :)
