### ISSUE TITLE
[Question] Is this DDMRP module, support customer sales forcast, at least to generate PO for purchasing of long lead time Raw Material?

### ISSUE THREAD

**Issue by bunhin** [ForgeFlow/ddmrp#75]
Dear @jbeficent, and all,

Very interesting project.
I have question whether it is support to use sales forecast from customer as the input information (demand estimate) to generate purchase order of Raw Material especially with long lead time.

For common example:
Customer will give monthly qty of order as forecast for 6 to 12 months ahead,  The accuracy will be +/- 20% of the estimated qty of order.

Since the lead time to buy raw material 3-4 months, we need to adopt the customer sales forecast as the base to order such raw materials.

Is this already supported with this DDMRP module? I read the dependencies seem already mention demand_estimate oca module, but no usage description yet on it.

would you please to give brief information on this, thank you.

with regards,
Bun Hin

**Comment by LoisRForgeFlow** [comment]
Hi @bunhin,

You can create the demand estimates with that information and make the buffers use a future-looking ADU calculation method which will consider that forecast to size your buffer. Reordering itself will never be directly attached to forecasts within the DDMRP methodology.
